server:
  port: 8800
  servlet:
    context-path: /steigenberger

#thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    check-template-location: true
  mvc:
    static-path-pattern: /**
  resources: 
    static-locations: classpath:/templates/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
    restart:
      enabled: true
