server:
  port: 8800
  servlet:
    context-path: /steigenberger

#thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    check-template-location: true
  devtools:
    restart:
      enabled: false
#mail
  mail:
     host: smtp.qq.com
     username: 123@qq.com
     password: 123123122qq
     properties:
           mail:
              smtp:
                auth: true
                starttls:
                    auth: true   
   
qhc:     
    frye: 
        protocal: http
        server: localhost
        port: 8801
        application: frye


    
